version: '3'

services:
  teste-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgresql/data:/var/lib/postgresql/data
